Repository NoCountrySimulacion/EasyTurnos, pull requests merged in 2024-06, with the labels that each got.

#24 18 backAppointmentCRUD
  Backend/API/Controllers/AppointmentController.cs
  Backend/Core/ServiceExtensions.cs
  Backend/Core/Services/AppointmentService.cs
  Backend/Core/Services/Interfaces/IAppointmentService.cs
  Backend/Core/Validators/AppointmentAddValidator.cs
  Backend/DTOs/Appointment/AppointmentAddDto.cs
  Backend/DTOs/Appointment/AppointmentFilterDto.cs
  Backend/DTOs/Appointment/AppointmentGetDto.cs
  Backend/DTOs/DTOs.csproj
  Backend/Infrastructure/Data/ApplicationDbContext.cs
  Backend/Infrastructure/Repositories/AppointmentRepository.cs
  Backend/Infrastructure/Repositories/Interfaces/IAppointmentRepository.cs
  Backend/Infrastructure/ServiceExtensions.cs
  Backend/Mappings/Profiles/AppointmentProfile.cs
Labels: enhancement

#34 Frontend Add Customer Form
  Frontend/public/images/Formulario.png
  Frontend/src/layout/Icons/Icons.tsx
  Frontend/src/layout/components/sidemenu/SideMenu.tsx
  Frontend/src/layout/pages/LayoutApp.tsx
  Frontend/src/professional/components/icons/Icons.tsx
  Frontend/src/professional/pages/AddClientForm.tsx
  Frontend/src/routes/AppRoutes.tsx
Labels: Desig

#58 refactor: AddButtonVolver
  Frontend/src/professional/pages/UserViewInd.tsx
Labels: Desig

#59 43 back UpdateAppointmentCRUD
  Backend/API/Controllers/AppointmentController.cs
  Backend/Core/Services/AppointmentService.cs
  Backend/Core/Services/Interfaces/IAppointmentService.cs
  Backend/Core/Validators/AppointmentAddValidator.cs
  Backend/DTOs/Appointment/AppointmentAddDto.cs
  Backend/DTOs/Appointment/AppointmentFilterDto.cs
  Backend/DTOs/Appointment/AppointmentGetDto.cs
  Backend/Domain/Entities/Appointment.cs
  Backend/Infrastructure/Data/ApplicationDbContext.cs
  Backend/Infrastructure/Repositories/AppointmentRepository.cs
  Backend/Infrastructure/Repositories/Interfaces/IAppointmentRepository.cs
  Backend/Utilities/Enums/Status.cs
Labels: enhancement

#76 75 back IncludeClientNameInGetAppointment
  Backend/API/Controllers/AppointmentController.cs
  Backend/Core/Services/AppointmentService.cs
  Backend/Core/Services/Interfaces/IAppointmentService.cs
  Backend/DTOs/Appointment/AppointmentGetDto.cs
  Backend/Infrastructure/Repositories/AppointmentRepository.cs
  Backend/Mappings/Profiles/AppointmentProfile.cs
Labels: enhancement

#92 89 --- FrontedAddReadme
  Frontend/README.md
Labels: documentation

#93 90-FrontendAddLogo
  Frontend/index.html
  Frontend/public/svgs/Logo_2.svg
  Frontend/public/svgs/favicon.svg
  Frontend/public/svgs/logo.svg
  Frontend/src/landing/components/banner/Banner.tsx
  Frontend/src/landing/components/testimonialCards/TestimonialCard.tsx
  Frontend/src/landing/components/testimonialCards/TestimonialCarousel.tsx
  Frontend/src/landing/components/testimonialCards/mock/testimonials.ts
  Frontend/src/landing/pages/Landing.tsx
  Frontend/src/layout/components/footer/Footer.tsx
  Frontend/src/layout/components/navbar/Logo.tsx
  Frontend/src/layout/components/sidemenu/SideMenu.tsx
  Frontend/src/layout/context/searchProvider.tsx
  Frontend/src/professional/pages/AddClientForm.tsx
  Frontend/src/professional/pages/UserViewInd.tsx
  Frontend/src/services/api/professionalClient.ts
Labels: Desig

#100 99_FrontendRefactorFormClients
  Frontend/src/layout/components/sidemenu/SideMenu.tsx
  Frontend/src/professional/pages/AddClientForm.tsx
Labels: documentation, Desig
